---
- name: Deploy Docker Container
  hosts: localhost
  become: true
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "prakharsharma404/scientific-calculator"
        source: pull

    - name: Stop Existing Container
      shell: docker rm -f calculator || true

    - name: Run Docker Container
      shell: docker run -d --name calculator prakharsharma404/scientific-calculator
